name: Run NEORV32 FreeRTOS Demo

on:
  push:
  workflow_dispatch:

jobs:

  neorv32-freertos-demo:
    runs-on: ubuntu-20.04

    steps:

    - name: '📂 Repository checkout'
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive

    - name: '📦 Install RISC-V GCC'
      run: |
        wget -q https://github.com/stnolting/riscv-gcc-prebuilt/releases/download/rv32i-131023/riscv32-unknown-elf.gcc-13.2.0.tar.gz
        mkdir $GITHUB_WORKSPACE/riscv-gcc
        tar -xzf riscv32-unknown-elf.gcc-13.2.0.tar.gz -C $GITHUB_WORKSPACE/riscv-gcc
        echo $GITHUB_WORKSPACE/riscv-gcc/bin >> $GITHUB_PATH

    - name: '📦 Install GHDL'
      uses: ghdl/setup-ghdl-ci@nightly

    - name: '🔍 Check tools'
      run: |
        riscv32-unknown-elf-gcc -v
        ghdl -v

    - name: '⚙️ Run FreeRTOS demo'
      run: /bin/bash -c "chmod u+x $GITHUB_WORKSPACE/demo/sim.sh && $GITHUB_WORKSPACE/demo/sim.sh"
